name: mood_flow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.16.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path: ^1.9.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.6.1
  screen_retriever: ^0.2.0
  sqlite3_flutter_libs: ^0.5.20
  window_manager: ^0.5.1
  launch_at_startup: ^0.2.0
  system_tray: ^2.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.16.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.1

dependency_overrides:
  frontend_server_client: ^4.0.0
  build_runner_core: ^9.0.0
  uuid: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/